version: '3.3'

services:
  travel-diary-view-server-project:
    image: travel-diary-view-server-project
    container_name: travel-diary-view-server-project
    command: /usr/sbin/apache2ctl -D FOREGROUND
    volumes:
      - ./src/:/var/www/html
      - ./test/:/root/test
    ports:
      - '20022:22'
      - '20080:80'
      - '28080:8080'
    expose:
      - '20022'
      - '20080'
      - '28080'
